version: "3.5"

# This compose file is for deployment with `docker stack deploy`
# The main difference between docker-compose.yml and this file is
# that we create a volume on the host to persist the database.

# When deploying, replace DOCKER_IMAGE_TAG with the tag of the build that you
# want to deploy.
# You will also need to provide files `secret_key`, `gis_user`, and
# `gis_password` holding the secrets needed to run the api.

services:
  gis:
    image: mdillon/postgis:11
    deploy:
      replicas: 1
    environment:
      POSTGRES_DB: "gis"
      POSTGRES_PASSWORD_FILE: "/run/secrets/gis_password"
      POSTGRES_USER_FILE: "/run/secrets/gis_user"
      ALLOW_IP_RANGE: "0.0.0.0/0"
    volumes:
      - /data/volumes/gis:/var/lib/postgresql
    secrets:
      - gis_user
      - gis_password
  api:
    image: mggg/districtr-api:API_IMAGE_TAG
    environment:
      POSTGRES_DB: gis
      POSTGRES_PORT: 5432
      POSTGRES_HOST: gis
      VIRTUAL_HOST: districtr.mggg.org
      LETSENCRYPT_HOST: districtr.mggg.org
      LETSENCRYPT_EMAIL: max.hully@gmail.com
    ports:
      - "3000:3000"
    depends_on:
      - gis
    deploy:
      replicas: 2
    secrets:
      - secret_key
      - gis_user
      - gis_password
  nginx-proxy:
    image: jwilder/nginx-proxy
    deploy:
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    deploy:
      replicas: 1
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhostd:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy

secrets:
  secret_key:
    file: /data/ops/secrets/secret_key
  gis_user:
    file: /data/ops/secrets/gis_user
  gis_password:
    file: /data/ops/secrets/gis_password

volumes:
  certs:
  vhostd:
  html:
  dhparam: