"""empty message

Revision ID: 013226c930e2
Revises: 5b3b103966a4
Create Date: 2019-02-07 10:29:59.038945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013226c930e2'
down_revision = '5b3b103966a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('column', sa.Column('election_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'column', 'election', ['election_id'], ['id'])
    op.drop_column('column', 'is_id_column')
    op.drop_constraint('place_id_column_id_fkey', 'place', type_='foreignkey')
    op.drop_column('place', 'id_column_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('id_column_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('place_id_column_id_fkey', 'place', 'column', ['id_column_id'], ['id'])
    op.add_column('column', sa.Column('is_id_column', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'column', type_='foreignkey')
    op.drop_column('column', 'election_id')
    op.drop_table('election')
    # ### end Alembic commands ###
