"""empty message

Revision ID: 105ca9af8e21
Revises: 7b4e3f607b6a
Create Date: 2019-05-14 13:00:37.258053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105ca9af8e21'
down_revision = '7b4e3f607b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_set', sa.Column('total_id', sa.Integer(), nullable=True))
    op.drop_constraint('column_set_total_fkey', 'column_set', type_='foreignkey')
    op.create_foreign_key(None, 'column_set', 'column', ['total_id'], ['id'])
    op.drop_column('column_set', 'total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_set', sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'column_set', type_='foreignkey')
    op.create_foreign_key('column_set_total_fkey', 'column_set', 'column', ['total'], ['id'])
    op.drop_column('column_set', 'total_id')
    # ### end Alembic commands ###
