"""empty message

Revision ID: 22b0be07ec4e
Revises: 013226c930e2
Create Date: 2019-02-07 12:15:24.553287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b0be07ec4e'
down_revision = '013226c930e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tileset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('source_url', sa.String(length=256), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=True),
    sa.Column('source_layer', sa.String(length=80), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tileset')
    # ### end Alembic commands ###
