"""empty message

Revision ID: 360dfa577dda
Revises: 6d5d638a0f26
Create Date: 2019-05-14 17:30:35.379734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360dfa577dda'
down_revision = '6d5d638a0f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('parts', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'parts')
    # ### end Alembic commands ###
