"""Initialize place table (plans and users are already there)

Revision ID: 500eb10c8e42
Revises:
Create Date: 2019-01-18 18:50:24.638823

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "500eb10c8e42"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("place")
    # ### end Alembic commands ###
