"""empty message

Revision ID: 76d5771b3125
Revises: 22b0be07ec4e
Create Date: 2019-02-07 13:00:32.792068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d5771b3125'
down_revision = '22b0be07ec4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districting_problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_of_parts', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('plural_noun', sa.String(length=256), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('tileset', 'source_layer',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('tileset', 'source_type',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('tileset', 'source_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('tileset', 'type',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tileset', 'type',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('tileset', 'source_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('tileset', 'source_type',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('tileset', 'source_layer',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_table('districting_problem')
    # ### end Alembic commands ###
