"""empty message

Revision ID: 7b4e3f607b6a
Revises: 5e03e4e5a458
Create Date: 2019-05-14 12:57:30.480348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4e3f607b6a'
down_revision = '5e03e4e5a458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_set', sa.Column('slug', sa.String(length=80), nullable=False))
    op.create_index(op.f('ix_unit_set_slug'), 'unit_set', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_set_slug'), table_name='unit_set')
    op.drop_column('unit_set', 'slug')
    # ### end Alembic commands ###
