"""empty message

Revision ID: 8ac3fe959520
Revises: 3add3e2f940a
Create Date: 2019-05-24 13:44:52.923163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac3fe959520'
down_revision = '3add3e2f940a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districting_problem', sa.Column('units', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('districting_problem', 'units')
    # ### end Alembic commands ###
