"""empty message

Revision ID: 96d3e8caaf8d
Revises: 105ca9af8e21
Create Date: 2019-05-14 13:16:53.242861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d3e8caaf8d'
down_revision = '105ca9af8e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unit_set_slug', table_name='unit_set')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unit_set_slug', 'unit_set', ['slug'], unique=True)
    # ### end Alembic commands ###
