"""Create user and plan tables

Revision ID: a414cc45796b
Revises: 500eb10c8e42
Create Date: 2019-01-18 19:45:55.708695

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a414cc45796b"
down_revision = "500eb10c8e42"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first", sa.String(length=80), nullable=False),
        sa.Column("last", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("serialized", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plan")
    op.drop_table("user")
    # ### end Alembic commands ###
