"""empty message

Revision ID: be20d31316ea
Revises: 
Create Date: 2019-01-18 13:26:44.066173

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be20d31316ea"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("place")
    # ### end Alembic commands ###
