"""empty message

Revision ID: e0d291dce089
Revises: 7da95be6d8ab
Create Date: 2019-01-31 10:36:55.889920

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e0d291dce089"
down_revision = "7da95be6d8ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "column",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("min", sa.Float(), nullable=True),
        sa.Column("max", sa.Float(), nullable=True),
        sa.Column("sum", sa.Float(), nullable=True),
        sa.Column("is_id_column", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "place_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("district_types", sa.String(length=160), nullable=False),
        sa.Column("information", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("place", sa.Column("id_column_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "place", "column", ["id_column_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "place", type_="foreignkey")
    op.drop_column("place", "id_column_id")
    op.drop_table("place_request")
    op.drop_table("column")
    # ### end Alembic commands ###
