"""empty message

Revision ID: e280cf0f2174
Revises: 0927f1ad4696
Create Date: 2019-05-14 12:43:25.843613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e280cf0f2174'
down_revision = '0927f1ad4696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_set', sa.Column('id_column_id', sa.Integer(), nullable=True))
    op.add_column('unit_set', sa.Column('name_column_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unit_set', 'column', ['name_column_id'], ['id'])
    op.create_foreign_key(None, 'unit_set', 'column', ['id_column_id'], ['id'])
    op.drop_column('unit_set', 'id_column_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_set', sa.Column('id_column_key', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'unit_set', type_='foreignkey')
    op.drop_constraint(None, 'unit_set', type_='foreignkey')
    op.drop_column('unit_set', 'name_column_id')
    op.drop_column('unit_set', 'id_column_id')
    # ### end Alembic commands ###
